# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Boris Tatarintsev
title: Software Engineer
email: ttyv00@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: risboo6909
github_username:  risboo6909
instagram_username: risboo6909
linkedin_username: boris-tatarintsev-443a0973
youtube_username: risboo6909

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Boris.

  I am a dedicated Software Engineer with extensive experience in developing high-load, real-time systems and backend services. 
  I have a Specialist degree in Cybernetics from MIREA, where I focused on creating automated systems.
  I have practical experience with <mark>Python</mark>, <mark>Golang</mark>, and <mark>Java</mark>, and have extensively worked with
  <mark>AWS</mark> and <mark>Serverless</mark> solutions. My expertise includes developing scalable and fault-tolerant systems that handle thousands of requests per second.

  In my free time, I enjoy programming in <mark>Rust</mark> and am always open to learning new technologies. 
  I have a strong interest in machine learning and continuously seek opportunities to expand my knowledge and skills.

  And btw, I'm a huge fan of [Advent of Code](https://adventofcode.com/), please don't hesitate to participate if you haven't already!

  I currently reside in Amsterdam, Netherlands, and am open to new opportunities in the tech industry.

content:
  - title: Personal projects
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        additional_links:
          - title:  risboo6909
            icon: fab fa-github
            url: https://github.com/risboo6909
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Please take a look at my github where I publsh my personal projects time to time.
        description: | # this will include new lines to allow paragraphs
          Also, please chekout some of my projects:

          * [Galton board simulation written in Rust/WebAssembly](https://risboo6909.org/quincunx/)
          * [Koch snowflake fractal](https://risboo6909.org/koch/)
          * [Natural language date/time parser written in Rust](https://risboo6909.org/when/)

          All the source code is available on my [Github](https://github.com/risboo6909)


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Booking.com
        link: https://www.booking.com
        link_text: booking.com
        sub_title: Software engineer
        caption: 2023, January — Present
        quote: >
          Booking.com is a travel fare aggregator website and travel metasearch engine for lodging reservations.
        description: |
          At Booking, I work as a Software Engineer, where I develop the order search system used by 
          numerous services within the company. Our system handles thousands of requests per second with very high 
          fault tolerance and low response times. Additionally, I have extensively worked with AWS, 
          particularly with Serverless solutions, such as Lambdas, Step-Functions, OpenSearch, MSK and etc.

          I am responsible for ensuring the reliability and efficiency of the search system as well, 
          which is critical for the smooth operation of various services.
           
          My role involves collaborating with cross-functional teams to continuously improve the performance and resilience of our systems.

      - layout: left
        title: Avito
        link: https://www.avito.ru
        link_text: avito.ru
        sub_title: Software engineer
        caption: April 2021 - December 2022
        quote: >
          Avito is the largest classified advertisements website in Russia and is one of the top 3 classified websites in the world.
        description: |
            Responsibilities:
              * Developing Information Cards: Create detailed and user-friendly information cards for various items, utilizing microservice architecture with Golang and Python.
              * Architectural Design: Actively participate in the design and development of scalable and efficient architecture for our systems.
              * Conducting Interviews: Lead and conduct interviews to assess technical skills and cultural fit of potential candidates.
              * Mentorship: Provide guidance and mentorship to newcomers, helping them integrate smoothly into the team and enhancing their technical skills.
              
            Example links to demonstrate what I was working on (backend part):
              - [iPhone 11 Reviews](https://www.avito.ru/catalog/phones/apple/iphone_11/reviews-ASgBAgICA0SywA2kmzm0wA3OqznQvA6u8tsC)
              - [iPhone 11 Pro Max Specifications](https://www.avito.ru/catalog/phones/apple/iphone_11_pro_max/specs-ASgBAgICA0SywA2KkTm0wA3OqznQvA78m9EB)

      - layout: left
        title: Ozon
        link: https://www.ozon.ru
        link_text: ozon.ru
        sub_title: Software engineer
        caption: 2019, January — 2021, April
        quote: >
          Ozon is a Russian e-commerce company specializing in online shopping.
        description: |
          I am responsible for developing infrastructure services at Ozon, which include:
            * Company map
            * Employee search
            *	Vacation reservations
            *	Organizational structure view
            *	Company goals
            *	Employee reviews
            * And more

          We use Golang as our main programming language for backend development, and Python for auxiliary tasks such as integration tests and utilities. Our data storage solution is PostgreSQL, 
          and we use Ceph for storing dynamic content such as pictures and documents.

      - layout: left
        title: Yandex
        link: https://www.yandex.ru
        link_text: yandex.ru
        sub_title: Software engineer
        caption: 2017 - 2019
        quote: >
          Yandex is a Russian corporation specializing in Internet-related products and services.
        description: |
          Developing the backend for a high-load video service using Python. The service I worked on is responsible for:

            * Serving various types of playlists (m3u8, DASH, MSS) to end users.
            * Balancing users among our CDNs for better performance and throughput.

          We achieved the capability to serve approximately 1TB of video content per second.

      - layout: left
        title: Yandex
        link: https://www.yandex.ru
        link_text: yandex.ru
        sub_title: Software engineer
        caption: 2011 - 2017
        quote: >
          Yandex is a Russian corporation specializing in Internet-related products and services.
        description: |
          Development of a real-time cross-datacenter high-load monitoring system using Python, JavaScript, Tornado, Redis, and MongoDB.

          Our monitoring system leverages a wide range of technologies, including Pyro, Redis, MongoDB, and Tornado 
          for asynchronous network interactions, as well as JavaScript. It is capable of handling thousands of machines distributed across all 
          Yandex data centers with very low latency (~5 seconds).

      - layout: left
        title: Glu mobile ltd (Moscow)
        link: https://www.glu.com
        link_text: glu.com
        sub_title: Software engineer
        caption: 2007 - 2011
        quote: >
          Glu Mobile is a developer and publisher of mobile games for smartphone and tablet devices.
        description: |
          Mobile games development and porting to various mobile platforms

      - layout: left
        title: Superscape Limited (Moscow)
        sub_title: Software engineer
        caption: 2006 - 2007
        quote: >
          Superscape Limited was a British company that developed and licensed software for the creation and playback of 3D mobile games.
        description: |
          Development and porting of Java games to mobile phones (j2me)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Moscow University of Radioengineering, Electronics and Automatics
        link: https://english.mirea.ru/
        # link_text: mirea.ru
        caption: 2000 - 2005
        sub_title: Specialist degree (equivalent to Master's degree)
        quote: >
          Moscow University of Radioengineering, Electronics and Automatics is a technical university in Moscow, Russia.
        description: | # this will include new lines to allow paragraphs
          I studied at MIREA in the Faculty of Cybernetics for 5 years and received a Specialist degree. 
          My studies focused on the creation of automated systems, providing me with a strong foundation 
          in programming and applied mathematics. My diploma thesis was dedicated to the application 
          of neural networks for predicting various events, which was quite an innovative field at the time.

          During my studies, I also participated in several projects that enhanced my practical experience 
          in system design and implementation. This hands-on experience, combined with my theoretical 
          knowledge, has equipped me with the skills necessary to tackle complex problems in the field of 
          cybernetics and beyond. My education at MIREA has prepared me well for a career in cutting-edge 
          technology and innovation.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Playing chess
      - Gaming
      - Reading
      - Watching movies
      - Traveling

      Look at this cool image I made
      ![Amsterdam](/cv/images/amsterdam.jpg "Amsterdam")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
